### ISSUE TITLE
Feature request: Provide a simple command line interface

### ISSUE THREAD

**Issue by cool-RR** [fireeye/pywintrace#17]
I want to run:

    c:\> pywintrace --type=CreateProcess --path=whatever

And get an infinite output of all the events that match my criteria.

**Comment by abergl** [comment]
Unsure what you mean exactly. You can modify one of the examples to do this using the kernel process provider.

**Comment by cool-RR** [comment]
What I mean is a CLI utility that one could use to track Windows events from the command line, without needing to know how pywintrace works and without having to develop a solution. That's a pretty big ask so if it's out of the scope of this project, I'd understand.

**Comment by abergl** [comment]
Closing issue.
