### ISSUE TITLE
Major slowdown when tracing CLR provider live, not seen with perfview

### ISSUE THREAD

**Issue by tom-bowles** [fireeye/pywintrace#21]
When I run the code below to trace the GC keyword from the CLR Runtime provider (https://docs.microsoft.com/en-us/dotnet/framework/performance/clr-etw-providers), I see a large slowdown in all managed code on my machine - eg. running a build of a C# project in VS goes from 1m30s to >6 minutes. However, when I run `perfview /GCCollectOnly`, which based on its source code appears to enable a larger set of keywords on this and other providers, and uses the same level (Informational), I don't see this slowdown.

I guess it might be because perfview is tracing direct to a file rather than using a callback, but I'm surprised that would make such a huge difference to the instrumented code. I thought the whole point of ETW was to be minimally intrusive. I don't see any additional filtering available on this provider besides the keywords and level.

```
import etw

providers = [
    etw.ProviderInfo('CLR', etw.GUID('{E13C0D23-CCBC-4E12-931B-D9CC2EEE27E4}'), any_keywords=[1]),
]

with etw.ETW(providers=providers, event_callback=lambda evt: ()):
    etw.run('etw')
```

Perfview has

```
            if (GCCollectOnly)
            {
                // TODO this logic is cloned.  We need it in only one place.  If you update it do the other location as well
                // The process events are so we get process names.  The ImageLoad events are so that we get version information about the DLLs 
                KernelEvents = KernelTraceEventParser.Keywords.Process | KernelTraceEventParser.Keywords.ImageLoad;
                ClrEvents = ClrTraceEventParser.Keywords.GC | ClrTraceEventParser.Keywords.Exception;
                ClrEventLevel = TraceEventLevel.Informational;
                TplEvents = TplEtwProviderTraceEventParser.Keywords.None;
                NoRundown = true;
                CommandProcessor.s_UserModeSessionName = "PerfViewGCSession";
                DataFile = "PerfViewGCCollectOnly.etl";
            }
```

**Comment by abergl** [comment]
I'm not sure how this is related to pywintrace. Filtering provider's messages is done by using keywords and level. Have you tried using `all_keywords` instead of `any_keywords`?. If the python process is utilizing too much CPU, you may use `callback_wait_time` parameter.

**Comment by tom-bowles** [comment]
I also am unsure how this relates to pywintrace, but it only happens with pywintrace and not with other consumers (such as PerfView) that use the same provider, level and keyword. There's no problem with the python CPU use, just the severe slowdown in monitored apps.

I did try all_keywords, with the same outcome. Tomorrow I'll see if there's any way I can externally inspect the session to find out whether the keyword filtering is taking effect.

**Comment by abergl** [comment]
That is strange, but indicates that the .NET framework itself is at fault. Like you mentioned, ETW tracing is designed to be lightweight, only logging when the provider is enabled. Since the provider would be enabled in either case (pywintrace and perfview), it seems odd that pywintrace would be causing the slowdown.

**Comment by tom-bowles** [comment]
Yes, it certainly seems odd but that's what I see. Until there's some clue why it's happening I don't think it's clear where the problem is.
 
I had a look at the sessions created by pywintrace and perfview and while it doesn't appear possible to directly inspect the providers, keywords, etc., one thing stands out: pywintrace's session is getting a very large number of dropped events ("Events Lost" in `tracelog -q`), thousands per second, whereas perfview is getting none. Maybe that's just because the callback is slower, or maybe it's because there are a lot more events somehow and it can't keep up.

**Comment by tom-bowles** [comment]
OK, figured it out. I was specifying a list of numeric keyword values for any_keywords, which isn't valid. It accepts either a list of keyword _names_ or bitmask. The result was that `get_keywords_bitmask` was returning 0 so I was getting all keywords, not the one I was expecting.

Not pywintrace's fault, .NET's fault or ETW's fault, but my fault :-)

**Comment by abergl** [comment]
Thanks for digging into that.
