### ISSUE TITLE
make consumer thread a daemon thread

### ISSUE THREAD

**Issue by EccoTheFlintstone** [fireeye/pywintrace#25]
In case the main thread crash because of bad coding from the user (or something unforeseen happens) , the interpreter  is not stopped because the consumer thread is still running.
To avoid that, one could make the consumer thread a daemon thread which wouldn't block the program from exiting in case of an error :

in etw.py (line 302):
```
self.process_thread = threading.Thread(target=self._run, args=(self.trace_handle, self.end_capture))
self.process_thread.daemon = True
self.process_thread.start()
```

**Comment by abergl** [comment]
Looks like this was added in https://github.com/fireeye/pywintrace/pull/26.

**Comment by abergl** [comment]
Closing issue since feature was added.
