### ISSUE TITLE
OSError: [WinError 1450] Insufficient system resources exist to complete the requested service - when running PyWinTrace

### ISSUE THREAD

**Issue by anapereira13** [fireeye/pywintrace#29]
I'm trying to run a Python script based on your Pywintrace code (firstly, thank you so much for creating this awesome solution!)

Initially I was able to run the script ~5 times without a problem, but since then I keep getting the following error:
OSError: [WinError 1450] Insufficient system resources exist to complete the requested service.

I don't know why it stopped working because nothing obvious changed about my environment. Also, I've tried to run the script on two separate machines (Windows 10) as well as on a Windows 7 VM, but I always get the same error. 

I found a potential solution for the 1450 error on two separate questions on StackOverflow, followed the steps for all machines, however, the problem persisted. Those steps included changing the registry entries "PoolUsageMax" and "PagedPoolSize" under memory management.

(The steps followed are from the answers on the following two questions:
https://stackoverflow.com/questions/53752487/oserror-winerror-1450-insufficient-system-resources-exist-to-complete-the-req

https://stackoverflow.com/questions/19845580/system-error-1450-has-occurred-insufficient-system-resources-exist-to-complete)

I realise this question is not specific to your product, but I can't find much else out there so I was wondering if you might have had a similar experience in the past and/or have any clues as to how I can fix this?

Thank you in advance.

Best,
Ana

**Comment by abergl** [comment]
Are old capture sessions still running? Check by running the `logman -ets` command. If they are still running then stop them and see if the error persists. Using `logman -ets NAME stop`  will do this.

**Comment by abergl** [comment]
Closing do to lack of response from OP.
