### ISSUE TITLE
how to find the process

### ISSUE THREAD

**Issue by SuperXiaoxiong** [fireeye/pywintrace#3]
thanks:
    I am new to the etw with 3 questions.
1. how to log the result with windows10?  the result are print on the command and I wonder how can I log it
2. the description was print in byte? how could convert it to utf-8 because there is nothing I can read
3. When I monitor the dns request, how could I defind which process launch the dns Or is the anyother way to locate which dns launched by the process

**Comment by abergl** [comment]
1. Use the --logfile command line argument.
2. The description coming from the event may or may not convert to UTF-8 properly. This is one of the reasons that we used bytes.
3. The ProcessId field in the event header contains the process PID.

**Comment by abergl** [comment]
@SuperXiaoxiong Does my previous response answer your questions?

**Comment by SuperXiaoxiong** [comment]
Thanks first!
the question2,3 is done ,but the log still won't be created
Here is my code 
```
import etw
def some_fuc():
    guid = {'Some provider': etw.GUID("{1C95126E-7EEA-49A9-A3FE-A378B03DDB4D}")}
    job = etw.ETW(guid)
    etw.run('etw',job, logfile='./testlog')
some_fuc()
```

**Comment by abergl** [comment]
You are welcome. Are you sure it isn't a permissions issue?

**Comment by SuperXiaoxiong** [comment]
thanks very much ！
It's ok now although I don't know why it don't work yesterday,
i really appreciate  your help
