### ISSUE TITLE
Windows 10 Microsoft-Windows-Kernel-Process Parse Error

### ISSUE THREAD

**Issue by insanitybit** [fireeye/pywintrace#4]
When parsing events from Microsoft-Windows-Kernel-Process ({22FB2CD6-0E7B-422B-A0C7-2FAD1FD0E716}) on Windows 10 it looks like PROCESSSTART events lead to the exception below.

I believe it's process start events causing this because just adding a 'try catch pass' block around the exception lets me view process start events, whereas without that error handling I do not see any start events.

Python 3.6.

> ValueError: invalid literal for int() with base 10: b''
> Traceback (most recent call last):
>   File "_ctypes/callbacks.c", line 234, in 'calling callback function'
>   File "C:\Users\Colin\Documents\win_events\pywinevent\etw\etw.py", line 662, in _processEvent
>     out.update(self._unpackSimpleType(record, info, property_array[i]))
>   File "C:\Users\Colin\Documents\win_events\pywinevent\etw\etw.py", line 549, in _unpackSimpleType
>     data = tdh.TDH_CONVERTER_LOOKUP[out_type](data)

This is the code I used to trigger the bug:

```python
import time
import etw

def handle_res(res):
    n, event = res
    if event['Task Name'] == 'PROCESSSTART':
        print(res)
    if event['Task Name'] == 'PROCESSSTOP':
        print(res)

if __name__ == '__main__':
    guid = {'Microsoft-Windows-Kernel-Process': etw.GUID("{22FB2CD6-0E7B-422B-A0C7-2FAD1FD0E716}")}
    job = etw.ETW(guid)
    job.start(handle_res)

    time.sleep(15)
    job.stop()
```

**Comment by abergl** [comment]
Thank you for the report. I have been able to reproduce the issue and have uploaded a fix to the proc_fix branch. Please switch to that branch and confirm it works for you.

**Comment by insanitybit** [comment]
Yep, with the proc_fix branch I'm seeing events, no more exception. Thanks.

**Comment by abergl** [comment]
No problem. Fix is in master. Closing issue.
