### ISSUE TITLE
multiple providers

### ISSUE THREAD

**Issue by dootyfree** [fireeye/pywintrace#7]
hello,

trying to use multiple providers using add_provider, second provider added does not seem to work as no events from second provider

using:

providers = [etw.ProviderInfo('Some Provider', etw.GUID("{11111111-1111-1111-1111-111111111111}"))]
provider2 = [etw.ProviderInfo('Some Provider2', etw.GUID("{11111111-1111-1111-1111-111111111112}"))]

job =  etw.ETW(providers=providers, event_callback=something)

job.add_provider(provider2)

thanks!

**Comment by abergl** [comment]
The add_provider method takes a single ProviderInfo instance, not a list.

**Comment by dootyfree** [comment]
Ok, thanks.   so... 

provider2 = etw.ProviderInfo('Some Provider2', etw.GUID("{11111111-1111-1111-1111-111111111112}"))

doesn't seem to work either.

Also trying 

providers = [etw.ProviderInfo('Some Provider', etw.GUID("{11111111-1111-1111-1111-111111111111}")),etw.ProviderInfo('Some Provider2', etw.GUID("{11111111-1111-1111-1111-111111111112}"))]


Is there a "correct" way to call multiple providers in one session?

**Comment by abergl** [comment]
Passing a list to the ETW class is the recommended way to capture on multiple providers. Have you confirmed that your flags and information level are correct? You may want to run the capture as administrator if not doing so already.

**Comment by dootyfree** [comment]
Yeah, am running as administrator, and using simple.py as a test, so very basic.  no filters.  Want all events to test.  weird part is am getting all events from "2" and not "1".  "1" works if used independently.

**Comment by dootyfree** [comment]
could it be the buffer is not large enough?

**Comment by abergl** [comment]
Unlikely. I would ensure that the providers are not being used by another capture by using the logman -ets command and querying running captures. The type provider details may be found here https://msdn.microsoft.com/en-us/library/windows/desktop/aa363668(v=vs.85).aspx

**Comment by dootyfree** [comment]
yep, stopped some related ones that were running...still same.  Added more providers to list, same result... only provider "2" events are returned.  Seem like the first one to engage wins, rest are shut out.  Is it possible for you to provide a working example using multiple providers??? something is not jiving here  :)

**Comment by abergl** [comment]
I did exactly as you showed using WinInet and process providers using simple.py without issue. I would make sure that you have installed the package or are using the -m argument when testing.

**Comment by dootyfree** [comment]
Ok, thank you sir, different results after rebooting.  It's windows!!!

**Comment by abergl** [comment]
Your welcome. Closing issue.
